export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const VALIDATE_ERROR = 'VALIDATE_ERROR';
export const VALIDATE_SUCCESS = 'VALIDATE_SUCCESS';
export const CHANGE_APP_LANGUAGE = 'CHANGE_APP_LANGUAGE';
